### ISSUE TITLE
Doesn't convert pdf files to video

### ISSUE THREAD

**Issue by abcool** [fangfufu/Converting-Arbitrary-Data-To-Video#1]
Tried below command:
sh mp42file.sh $HadoopBook.pdf $sample.mp4

Getting this error:
moov atom not found
.mp4: Invalid data found when processing input

**Comment by fangfufu** [comment]
I don't understand why you put ``$`` in front of your filenames. Maybe you need a different ffmpeg version. These have been tested under Debian Bookworm's ffmpeg.

**Comment by abcool** [comment]
tried without $ also same error. Installing ffmpeg using brew.

**Comment by fangfufu** [comment]
Well, the whole ``$`` is just shell filename replacement...
